# Generated by Django 5.2.12 on 2026-07-28 19:51

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthFit', '0015_alter_attendence_unique_together_and_more'),
        ('Gym', '0030_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sponsor_logo')),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Rich text (HTML from the editor). Sanitized on save.')),
                ('type', models.CharField(choices=[('announcement', 'Platform Announcement'), ('notification', 'Notification'), ('promotion', 'Promotion'), ('advertisement', 'Advertisement'), ('campaign', 'Campaign'), ('release', 'Product Release'), ('maintenance', 'Maintenance Notice'), ('survey', 'Survey'), ('event', 'Event'), ('offer', 'Offer')], db_index=True, default='announcement', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='communication_image')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='communication_attachment')),
                ('external_link', models.URLField(blank=True)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('channel_push', models.BooleanField(default=True, help_text='Firebase Cloud Messaging (mobile).')),
                ('channel_web_push', models.BooleanField(default=True, help_text='Browser / PWA web push.')),
                ('channel_pwa', models.BooleanField(default=True, help_text='PWA in-app notification center.')),
                ('channel_email', models.BooleanField(default=False, help_text='Future — no sender implemented yet.')),
                ('channel_whatsapp', models.BooleanField(default=False, help_text='Future — no sender implemented yet.')),
                ('channel_sms', models.BooleanField(default=False, help_text='Future — no sender implemented yet.')),
                ('show_popup', models.BooleanField(default=False)),
                ('show_banner', models.BooleanField(default=False)),
                ('show_notification_center', models.BooleanField(default=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_success_count', models.PositiveIntegerField(default=0)),
                ('dispatch_failure_count', models.PositiveIntegerField(default=0)),
                ('total_impressions', models.PositiveIntegerField(default=0, help_text="Incremented once per recipient the first time it's shown in their notification center / home feed.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='communications.communicationcampaign')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
                'ordering': ['-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('everyone', 'Everyone'), ('all_members', 'All Members'), ('all_staff', 'All Staff'), ('all_owners', 'All Gym Owners'), ('all_receptionists', 'All Receptionists'), ('all_trainers', 'All Trainers'), ('specific_gym', 'Specific Gym(s)'), ('specific_plan', 'Members of Specific Plan (by name)'), ('subscription_plan', 'Gyms on Specific SaaS Plan'), ('specific_city', 'Specific City'), ('specific_state', 'Specific State'), ('specific_country', 'Specific Country'), ('specific_members', 'Specific Members'), ('specific_staff', 'Specific Staff'), ('active_members', 'Active Members'), ('expired_members', 'Expired Members'), ('expiring_members', 'Expiring Members')], db_index=True, default='everyone', max_length=30)),
                ('plan_name_filter', models.CharField(blank=True, help_text="Case-insensitive match against AuthFit.MembershipPlan.plan, e.g. 'Gold' matches every gym's Gold-named plan.", max_length=100)),
                ('cities', models.JSONField(blank=True, default=list, help_text='List of city names, matched case-insensitively against Gym.city.')),
                ('states', models.JSONField(blank=True, default=list, help_text='Not yet resolvable — Gym has no state field.')),
                ('countries', models.JSONField(blank=True, default=list, help_text='Not yet resolvable — Gym has no country field.')),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='communications.communication')),
                ('gyms', models.ManyToManyField(blank=True, related_name='+', to='Gym.gym')),
                ('plans', models.ManyToManyField(blank=True, related_name='+', to='AuthFit.membershipplan')),
                ('specific_members', models.ManyToManyField(blank=True, related_name='targeted_communications_as_member', to=settings.AUTH_USER_MODEL)),
                ('specific_staff', models.ManyToManyField(blank=True, related_name='targeted_communications_as_staff', to=settings.AUTH_USER_MODEL)),
                ('subscription_plans', models.ManyToManyField(blank=True, related_name='+', to='Gym.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Communication Audience',
                'verbose_name_plural': 'Communication Audiences',
            },
        ),
        migrations.CreateModel(
            name='CommunicationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('fcm', 'FCM (Mobile App)'), ('web_push', 'Web Push (Browser/PWA)'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('dismissed', 'Dismissed'), ('read', 'Read')], db_index=True, default='sent', max_length=20)),
                ('deduplication_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='communications.communication')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Gym.gym')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Delivery Log',
                'verbose_name_plural': 'Communication Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='communicationcampaign',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communications.communicationsponsor'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status', 'publish_at'], name='communicati_status_a20353_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['type'], name='communicati_type_d0ab61_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['priority'], name='communicati_priorit_4d18a4_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationdeliverylog',
            index=models.Index(fields=['communication', 'channel'], name='communicati_communi_f2294d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationdeliverylog',
            index=models.Index(fields=['communication', 'status'], name='communicati_communi_4c05b2_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationdeliverylog',
            index=models.Index(fields=['gym', 'created_at'], name='communicati_gym_id_5e5994_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationdeliverylog',
            constraint=models.UniqueConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), fields=('communication', 'deduplication_key'), name='unique_communication_dedup_key'),
        ),
    ]
