# Generated by Django 5.2.12 on 2026-07-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='banner_placement',
            field=models.CharField(blank=True, choices=[('home', 'Home Banner'), ('dashboard', 'Dashboard Banner'), ('carousel', 'Carousel'), ('top', 'Top Banner'), ('bottom', 'Bottom Banner')], default='home', help_text='Only used when show_banner is True.', max_length=20),
        ),
        migrations.AddField(
            model_name='communication',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='deep_link_type',
            field=models.CharField(blank=True, choices=[('', 'None — opens Communication Center'), ('attendance', 'Attendance'), ('billing', 'Billing'), ('workout', 'Workout'), ('member_profile', 'Member Profile'), ('reports', 'Reports'), ('shop', 'Shop'), ('website', 'Website (uses External Link)'), ('youtube', 'YouTube (uses External Link)'), ('instagram', 'Instagram (uses External Link)'), ('external_url', 'Other External URL (uses External Link)')], default='', help_text="Where tapping this communication should take the recipient. Internal screens route the mobile app the same way existing push payloads already do (e.g. 'screen': 'Profile'); the *_URL types use External Link.", max_length=20),
        ),
        migrations.AddField(
            model_name='communication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_dispatching',
            field=models.BooleanField(db_index=True, default=False, help_text="Transient guard held for the duration of one dispatch call. Prevents a double 'Publish Now' click or an overlapping cron tick from sending the same communication twice — see services.dispatch_communication's atomic claim/release."),
        ),
        migrations.AddField(
            model_name='communication',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='require_read',
            field=models.BooleanField(default=False, help_text='If set, a popup stays until the recipient explicitly presses Mark as Read — Dismiss alone does not satisfy this. Mirrors announcements.Announcement.require_read.'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommunicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_title_snapshot', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('bulk_action', 'Bulk Action')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='communications.communication')),
            ],
            options={
                'verbose_name': 'Communication Audit Log',
                'verbose_name_plural': 'Communication Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['communication', 'created_at'], name='communicati_communi_2267a8_idx'), models.Index(fields=['action'], name='communicati_action_560fa2_idx')],
            },
        ),
    ]
