# Generated by Django 5.2.12 on 2026-06-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthFit', '0001_initial'),
        ('Gym', '0004_gymgstprofile'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30)),
                ('financial_year', models.CharField(max_length=7)),
                ('invoice_date', models.DateField()),
                ('invoice_type', models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('bill_of_supply', 'Bill of Supply')], default='tax_invoice', max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=10)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('customer_state', models.CharField(max_length=100)),
                ('customer_state_code', models.CharField(max_length=2)),
                ('place_of_supply_state', models.CharField(max_length=100)),
                ('place_of_supply_code', models.CharField(max_length=2)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Gym.gym')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='AuthFit.enrollment')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Shop.order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac_code', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='e.g. 18.00 for 18%', max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_phone', models.CharField(max_length=10)),
                ('member_unique_id', models.CharField(max_length=10)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_duration_days', models.PositiveIntegerField(default=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('C', 'Cash'), ('U', 'UPI'), ('B', 'UPI + Cash')], max_length=1, null=True)),
                ('payment_date', models.DateField()),
                ('membership_start', models.DateField()),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='AuthFit.enrollment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Gym.gym')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.payment'),
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=7)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_counters', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Invoice Counter',
                'verbose_name_plural': 'Invoice Counters',
                'constraints': [models.UniqueConstraint(fields=('gym', 'financial_year'), name='unique_counter_per_gym_fy')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym', 'payment_date'], name='billing_pay_gym_id_e111d4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['gym', 'financial_year', 'invoice_number'], name='billing_inv_gym_id_be9f33_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['gym', 'invoice_date'], name='billing_inv_gym_id_9f21b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('gym', 'invoice_number', 'financial_year'), name='unique_invoice_number_per_gym_per_fy'),
        ),
    ]
