# Generated by Django 5.2.12 on 2026-07-27 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0029_pushnotificationlog'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='related_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.payment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('void', 'Void'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='issued', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount refunded (GST-inclusive).', max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('original', 'Original Payment Method')], default='original', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the refund was actually issued — used for revenue reporting attribution, deliberately independent of the original invoice_date.')),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='Gym.gym')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.invoice')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-refund_date', '-created_at'],
                'indexes': [models.Index(fields=['gym', 'refund_date'], name='billing_ref_gym_id_735ddf_idx'), models.Index(fields=['invoice'], name='billing_ref_invoice_2bece5_idx'), models.Index(fields=['gym', 'status'], name='billing_ref_gym_id_9221d4_idx')],
            },
        ),
    ]
