# Generated by Django 5.2.12 on 2026-07-07 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('gym_size', models.CharField(choices=[('lt_100', 'Less than 100 members'), ('100_300', '100–300 members'), ('300_700', '300–700 members'), ('gt_700', 'More than 700 members')], max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], default='en', max_length=20)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google'), ('direct', 'Direct'), ('other', 'Other')], default='website', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='demoRequest_phone_n_4d108d_idx')],
            },
        ),
    ]
