# Generated by Django 5.2.12 on 2026-07-24 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gym', '0024_add_gym_social_media_usernames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('rent', '🏠 Rent'), ('salary', '👨 Staff Salary'), ('electricity', '⚡ Electricity'), ('water', '💧 Water'), ('internet', '🌐 Internet'), ('cleaning', '🧹 Cleaning'), ('maintenance', '🛠 Maintenance'), ('equipment', '🏋 Equipment'), ('marketing', '📢 Marketing'), ('software', '💻 Software Subscription'), ('tax', '🧾 Tax'), ('refreshments', '🥤 Refreshments'), ('office', '📦 Office Supplies'), ('transport', '🚗 Transport'), ('repair', '🔧 Repair'), ('laundry', '🧺 Laundry'), ('security', '🛡 Security'), ('miscellaneous', '➕ Other')], db_index=True, default='miscellaneous', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('credit', 'Credit Card'), ('debit', 'Debit Card')], default='cash', max_length=10)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/%Y/%m/')),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['gym', 'expense_date'], name='expenses_ex_gym_id_134c1e_idx'), models.Index(fields=['gym', 'category'], name='expenses_ex_gym_id_0fbd70_idx')],
            },
        ),
    ]
