# Generated by Django 5.2.12 on 2026-07-24 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0024_add_gym_social_media_usernames'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('rent', '🏠 Rent'), ('salary', '👨 Staff Salary'), ('electricity', '⚡ Electricity'), ('water', '💧 Water'), ('internet', '🌐 Internet'), ('cleaning', '🧹 Cleaning'), ('maintenance', '🛠 Maintenance'), ('equipment', '🏋 Equipment'), ('marketing', '📢 Marketing'), ('software', '💻 Software Subscription'), ('tax', '🧾 Tax'), ('refreshments', '🥤 Refreshments'), ('office', '📦 Office Supplies'), ('transport', '🚗 Transport'), ('repair', '🔧 Repair'), ('laundry', '🧺 Laundry'), ('security', '🛡 Security'), ('miscellaneous', '➕ Other')], default='miscellaneous', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Starting amount. Later occurrences use the most recent non-deleted Expense's amount instead.", max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('credit', 'Credit Card'), ('debit', 'Debit Card')], default='cash', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateField(help_text='First month this template generates an Expense for.')),
                ('end_date', models.DateField(blank=True, help_text='Optional. Template stops generating after this date.', null=True)),
                ('next_run_date', models.DateField(db_index=True, help_text='Next date this template is due to generate an Expense. Advances automatically after each successful generation run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_templates_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_templates', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Recurring Expense Template',
                'verbose_name_plural': 'Recurring Expense Templates',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='expenses.expensetemplate'),
        ),
        migrations.AddIndex(
            model_name='expensetemplate',
            index=models.Index(fields=['gym', 'is_active', 'next_run_date'], name='expenses_ex_gym_id_6c6296_idx'),
        ),
    ]
