# Generated by Django 5.2.12 on 2026-07-02 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0001_initial'),
        ('Gym', '0009_gym_app_download_url_gym_app_name_gym_app_short_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='OWNER', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('gym', 'phone'), name='unique_pending_enrollment_phone_per_gym'),
        ),
    ]
