# Generated by Django 5.2.12 on 2026-06-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0001_initial'),
        ('Gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='EnrollmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=10)),
                ('previous_member_id', models.CharField(max_length=10)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('previous_pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('new_gym_joining_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=10)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='Gym.gym')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_records', to='AuthFit.enrollment')),
                ('previous_gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='Gym.gym')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['previous_gym', 'status'], name='AuthFit_enr_previou_947a5b_idx')],
            },
        ),
    ]
