# Generated by Django 5.2.12 on 2026-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_enrollment_profile_completed_enrollment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='initial_invoice_generated',
            field=models.BooleanField(default=False, help_text='Set once the up-front payment collected during Quick Enrollment has been converted into a Payment + Invoice.'),
        ),
    ]
