# Generated by Django 5.2.12 on 2026-06-20 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0002_enrollment_is_active_enrollmenttransfer'),
        ('Gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttransfer',
            name='previous_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmenttransfer',
            name='previous_plan_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='enrollmenttransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('previous_enrollment',), name='unique_pending_transfer_per_enrollment'),
        ),
    ]
