# Generated by Django 5.2.12 on 2026-07-03 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0003_enrollment_initial_invoice_generated'),
        ('Gym', '0009_gym_app_download_url_gym_app_name_gym_app_short_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_due_date', models.DateField(blank=True, null=True)),
                ('new_due_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_logs', to='AuthFit.enrollment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_logs', to='Gym.gym')),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AuthFit.membershipplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AuthFit.membershipplan')),
            ],
            options={
                'verbose_name': 'Membership Plan Change Log',
                'verbose_name_plural': 'Membership Plan Change Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'enrollment'], name='AuthFit_mem_gym_id_dd683b_idx')],
            },
        ),
    ]
