# Generated by Django 5.2.12 on 2026-07-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0004_membershipplanchangelog'),
        ('Gym', '0010_gym_upi_display_name_gym_upi_enabled_gym_upi_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='EnrollmentDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.IntegerField(db_index=True)),
                ('member_name', models.CharField(max_length=100)),
                ('member_phone', models.CharField(max_length=10)),
                ('delete_type', models.CharField(choices=[('duplicate', 'Duplicate Enrollment (permanent)'), ('soft', 'Delete Enrollment Only (soft delete)')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_deletion_logs', to='Gym.gym')),
                ('gym_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Deletion Log',
                'verbose_name_plural': 'Enrollment Deletion Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'enrollment_id'], name='AuthFit_enr_gym_id_a9f5df_idx')],
            },
        ),
    ]
