# Generated by Django 5.2.12 on 2026-07-11 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0005_enrollment_deleted_at_enrollment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='membership_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Actual membership start date. Used to calculate DueDate — lets owners backdate enrollment for members who joined before EnterGYM. Distinct from `doj` (record-creation date).'),
        ),
    ]
