# Generated by Django 5.2.12 on 2026-07-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0006_enrollment_membership_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='salary',
            new_name='charge',
        ),
    ]
