# Generated by Django 5.2.12 on 2026-07-17 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0007_rename_salary_trainer_charge'),
        ('Gym', '0019_gym_enable_geo_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['gym', 'unique_id'], name='AuthFit_enr_gym_id_68b2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['gym', 'phone'], name='AuthFit_enr_gym_id_f9d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['gym', 'paymentStatus'], name='AuthFit_enr_gym_id_1bb1b4_idx'),
        ),
    ]
