# Generated by Django 5.2.12 on 2026-07-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0008_enrollment_authfit_enr_gym_id_68b2c0_idx_and_more'),
        ('Gym', '0020_orphanuserdeletionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSupportQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('problem_type', models.CharField(choices=[('forgot_password', 'Forgot Password'), ('unable_login', 'Unable to Login'), ('account_locked', 'Account Locked'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gym.gym')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_support_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Support Query',
                'verbose_name_plural': 'Login Support Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='AuthFit_log_phone_208ff8_idx'), models.Index(fields=['status'], name='AuthFit_log_status_9fd4b3_idx'), models.Index(fields=['problem_type'], name='AuthFit_log_problem_ea2ad2_idx'), models.Index(fields=['created_at'], name='AuthFit_log_created_bd8dac_idx')],
            },
        ),
    ]
