# Generated by Django 5.2.12 on 2026-07-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0009_loginsupportquery'),
        ('Gym', '0021_equipmentbrand_gym_equipment_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-check', help_text="Font Awesome icon class, e.g. 'fa-dumbbell'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Gym Service',
                'verbose_name_plural': 'Gym Services',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['gym', 'is_active'], name='AuthFit_gym_gym_id_a796d5_idx')],
                'unique_together': {('gym', 'name')},
            },
        ),
    ]
