# Generated by Django 5.2.12 on 2026-07-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0010_gymservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymService',
        ),
    ]
