# Generated by Django 5.2.12 on 2026-07-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0012_gymqrcode_attendanceattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymNotification',
        ),
    ]
