# Generated by Django 5.2.12 on 2026-07-25 02:34

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0013_delete_gymnotification'),
        ('Gym', '0026_gym_dashboard_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='show_on_home',
            field=models.BooleanField(default=True, help_text="Show this plan in the pricing section of your gym's public homepage."),
        ),
        migrations.CreateModel(
            name='RegisterScanImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_public_id', models.CharField(blank=True, max_length=255)),
                ('raw_ai_response', models.JSONField(blank=True, default=list)),
                ('edited_response', models.JSONField(blank=True, default=list)),
                ('detected_count', models.PositiveIntegerField(default=0)),
                ('manual_count', models.PositiveIntegerField(default=0)),
                ('rows_edited', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('already_present_count', models.PositiveIntegerField(default=0)),
                ('needs_review_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_scan_imports', to='Gym.gym')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Register Scan Import',
                'verbose_name_plural': 'Register Scan Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegisterScanImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=10)),
                ('detected_time', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('ai', 'AI Detected'), ('manual', 'Manual')], default='ai', max_length=10)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('skipped_exists', 'Already Marked'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='AuthFit.registerscanimport')),
            ],
        ),
        migrations.AddIndex(
            model_name='registerscanimport',
            index=models.Index(fields=['gym', 'created_at'], name='AuthFit_reg_gym_id_06efc7_idx'),
        ),
        migrations.AddIndex(
            model_name='registerscanimport',
            index=models.Index(fields=['gym', 'status'], name='AuthFit_reg_gym_id_02ec97_idx'),
        ),
        migrations.AddIndex(
            model_name='registerscanimportrow',
            index=models.Index(fields=['import_batch'], name='AuthFit_reg_import__c8ce14_idx'),
        ),
    ]
