# Generated by Django 5.2.12 on 2026-07-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0014_membershipplan_show_on_home_registerscanimport_and_more'),
        ('Gym', '0030_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendence',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='AuthFit.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('gym', 'enrollment', 'date')},
        ),
    ]
