# Generated by Django 5.2.12 on 2026-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0015_alter_attendence_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerscanimport',
            name='credit_consumed',
            field=models.BooleanField(default=False, help_text='True once one AI credit has been deducted for this import. Guards against double-deduction if the same import is saved more than once (refresh/resubmit).'),
        ),
    ]
