# Generated by Django 5.2.12 on 2026-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0016_registerscanimport_credit_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerscanimport',
            name='summary_broadcasted',
            field=models.BooleanField(default=False, help_text='True once the single Live Attendance summary notification has been sent for this import. Guards against a duplicate broadcast if save is retried/double-clicked for the same import_batch.'),
        ),
    ]
