# Generated by Django 5.2.12 on 2026-07-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0017_registerscanimport_summary_broadcasted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
