# Generated by Django 5.2.12 on 2026-07-30 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0018_alter_attendence_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
