# Generated by Django 5.2.12 on 2026-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0019_alter_attendence_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text="Show this plan in the pricing section of your gym's public homepage."),
        ),
    ]
