# Generated by Django 5.2.12 on 2026-08-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0020_alter_membershipplan_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this plan from regular members. Only owners/receptionists can see and assign it.'),
        ),
    ]
