# Generated by Django 5.2.12 on 2026-07-08 20:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_platformsubscriptionpayment'),
        ('Shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflavor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flavor',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GlobalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_products_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalProductFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('global_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='Shop.globalproduct')),
            ],
            options={
                'ordering': ['flavor_name', 'weight'],
            },
        ),
        migrations.CreateModel(
            name='GymProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_products', to='Shop.globalproduct')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.gym')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='gym_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Shop.gymproduct'),
        ),
        migrations.CreateModel(
            name='GymProductFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('global_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.globalproductflavor')),
                ('gym_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='Shop.gymproduct')),
            ],
            options={
                'ordering': ['global_flavor__flavor_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='gym_flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.gymproductflavor'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductFlavor',
        ),
        migrations.AddIndex(
            model_name='globalproduct',
            index=models.Index(fields=['approval_status', 'active'], name='Shop_global_approva_49d496_idx'),
        ),
        migrations.AddIndex(
            model_name='globalproduct',
            index=models.Index(fields=['brand', 'category'], name='Shop_global_brand_6cbe68_idx'),
        ),
        migrations.AddIndex(
            model_name='globalproductflavor',
            index=models.Index(fields=['global_product'], name='Shop_global_global__ef5253_idx'),
        ),
        migrations.AddIndex(
            model_name='gymproduct',
            index=models.Index(fields=['gym', 'is_visible'], name='Shop_gympro_gym_id_e86fe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymproduct',
            constraint=models.UniqueConstraint(fields=('gym', 'global_product'), name='unique_gym_global_product'),
        ),
        migrations.AddIndex(
            model_name='gymproductflavor',
            index=models.Index(fields=['barcode'], name='Shop_gympro_barcode_ab6ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='gymproductflavor',
            index=models.Index(fields=['sku'], name='Shop_gympro_sku_79ef83_idx'),
        ),
        migrations.AddIndex(
            model_name='gymproductflavor',
            index=models.Index(fields=['gym_product', 'active'], name='Shop_gympro_gym_pro_6bb305_idx'),
        ),
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.UniqueConstraint(fields=('gym_product', 'global_flavor'), name='unique_gym_product_flavor'),
        ),
    ]
