# Generated by Django 5.2.12 on 2026-07-08 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_productflavor_product_remove_order_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment'), ('Damage', 'Damage'), ('Expired', 'Expired'), ('Returned', 'Returned')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock_after', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('gym_product_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Shop.gymproductflavor')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym_product_flavor', '-created_at'], name='Shop_gyminv_gym_pro_155601_idx'), models.Index(fields=['movement_type'], name='Shop_gyminv_movemen_f00738_idx')],
            },
        ),
    ]
