# Generated by Django 5.2.12 on 2026-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_add_inventory_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymproductflavor',
            name='low_stock_notified',
            field=models.BooleanField(default=False, help_text='Internal flag — prevents repeat low-stock alerts until stock recovers.'),
        ),
    ]
