# Generated by Django 5.2.12 on 2026-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_add_low_stock_notified_flag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='gymproductflavor_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock__gte', 0)), name='gymproductflavor_minimum_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__isnull', True), ('selling_price__gte', 0), _connector='OR'), name='gymproductflavor_selling_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='gymproductflavor_cost_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='gymproductflavor',
            constraint=models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), ('selling_price__isnull', True), ('discount_price__lte', models.F('selling_price')), _connector='OR'), name='gymproductflavor_discount_lte_selling'),
        ),
    ]
