# Generated by Django 5.2.12 on 2026-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_platformsubscriptionpayment'),
        ('Shop', '0005_add_price_stock_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymproduct',
            name='active',
            field=models.BooleanField(default=True, help_text="Soft-delete flag. False = removed from this gym's store but order history preserved."),
        ),
        migrations.AddIndex(
            model_name='gymproduct',
            index=models.Index(fields=['gym', 'active'], name='Shop_gympro_gym_id_1aa276_idx'),
        ),
    ]
