# Generated by Django 5.2.12 on 2026-07-08 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_platformsubscriptionpayment'),
        ('Shop', '0006_add_gymproduct_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gymproductflavor',
            name='Shop_gympro_barcode_ab6ef5_idx',
        ),
        migrations.RemoveField(
            model_name='gymproductflavor',
            name='barcode',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['gym', 'status'], name='Shop_order_gym_id_5ebf38_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['gym_product', 'status'], name='Shop_order_gym_pro_d47cb5_idx'),
        ),
    ]
