# Generated by Django 5.2.12 on 2026-07-23 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gym', '0024_add_gym_social_media_usernames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('show_popup', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=True)),
                ('save_inbox', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user (Owner/Receptionist) who sent this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_messages', to='Gym.gym')),
                ('member', models.ForeignKey(help_text='The single member this message is addressed to.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Message',
                'verbose_name_plural': 'Member Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym'], name='member_mess_gym_id_d5192b_idx'), models.Index(fields=['member'], name='member_mess_member__cbb7e4_idx'), models.Index(fields=['is_read'], name='member_mess_is_read_2a318b_idx'), models.Index(fields=['created_at'], name='member_mess_created_2cc35e_idx'), models.Index(fields=['gym', 'member', 'is_read'], name='member_mess_gym_id_2e39b3_idx')],
            },
        ),
    ]
