# Generated by Django 5.2.12 on 2026-07-22 02:08

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthFit', '0012_gymqrcode_attendanceattempt'),
        ('Gym', '0024_add_gym_social_media_usernames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Rich text (HTML from the editor). Sanitized on save.')),
                ('announcement_type', models.CharField(choices=[('offer', 'Offer'), ('instruction', 'Instruction'), ('alert', 'Alert'), ('holiday', 'Gym Holiday'), ('new_plan', 'New Plan'), ('event', 'Event'), ('maintenance', 'Maintenance'), ('payment_reminder', 'Payment Reminder'), ('trainer_update', 'Trainer Update'), ('general', 'General Notice')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='announcement_image')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='announcement_attachment')),
                ('external_link', models.URLField(blank=True)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_popup', models.BooleanField(default=False)),
                ('show_banner', models.BooleanField(default=False)),
                ('show_web', models.BooleanField(default=True)),
                ('show_mobile', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=False)),
                ('require_read', models.BooleanField(default=False, help_text='If set, High-priority popups stay until the member explicitly presses Mark as Read (Dismiss alone does not satisfy this).')),
                ('pin_home', models.BooleanField(default=False)),
                ('target_audience', models.CharField(choices=[('all', 'All Members'), ('active', 'Only Active Members'), ('expired', 'Expired Members'), ('plan', 'Members of Specific Plan'), ('trainer', 'Members of Specific Trainer'), ('specific', 'Specific Members')], default='all', max_length=10)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Incremented once per member the first time it enters their home/center feed. Best-effort counter, not a unique-visitor guarantee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Gym.gym')),
                ('target_members', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AuthFit.membershipplan')),
                ('target_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='AuthFit.trainer')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-pin_home', '-publish_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile App'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Read',
                'verbose_name_plural': 'Announcement Reads',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['gym', 'is_active', 'publish_at'], name='announcemen_gym_id_7670b6_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['gym', 'announcement_type'], name='announcemen_gym_id_785dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['gym', 'priority'], name='announcemen_gym_id_e1a78a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement', 'read_at'], name='announcemen_announc_2e0dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', 'announcement'], name='announcemen_user_id_bdf288_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read_per_user'),
        ),
    ]
