# Generated by Django 5.2.12 on 2026-07-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Members'), ('active', 'Only Active Members'), ('expired', 'Expired Members'), ('expiring_soon', 'Members Expiring in 3 Days'), ('plan', 'Members of Specific Plan'), ('trainer', 'Members of Specific Trainer'), ('specific', 'Specific Members')], default='all', max_length=20),
        ),
    ]
