# Generated by Django 5.2.12 on 2026-06-21 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_limit', models.PositiveIntegerField(default=100)),
                ('trainer_limit', models.PositiveIntegerField(default=5)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_name', models.CharField(max_length=100)),
                ('gym_code', models.SlugField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('member_limit', models.PositiveIntegerField(default=100)),
                ('trainer_limit', models.PositiveIntegerField(default=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('theme_color', models.CharField(default='#007bff', max_length=7)),
                ('receipt_footer', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('radius_meters', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_gym', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gym.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'ordering': ['gym_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_owner', 'Gym Owner'), ('trainer', 'Trainer'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='Gym.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'indexes': [models.Index(fields=['gym', 'role'], name='Gym_staffpr_gym_id_efe9d9_idx'), models.Index(fields=['user'], name='Gym_staffpr_user_id_1ce639_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['gym_code'], name='Gym_gym_gym_cod_2f80d8_idx'),
        ),
    ]
