# Generated by Django 5.2.12 on 2026-06-24 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='receipt_footer',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='theme_color',
        ),
        migrations.AlterField(
            model_name='gym',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gym_logo'),
        ),
    ]
