# Generated by Django 5.2.12 on 2026-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_remove_gym_receipt_footer_remove_gym_theme_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='enable_attendance',
            field=models.BooleanField(default=True, help_text='Geo-attendance and attendance analytics.'),
        ),
        migrations.AddField(
            model_name='gym',
            name='enable_face_recognition',
            field=models.BooleanField(default=True, help_text='Face recognition enrollment and auto check-in.'),
        ),
        migrations.AddField(
            model_name='gym',
            name='enable_store',
            field=models.BooleanField(default=True, help_text='Supplement store & order management.'),
        ),
        migrations.AddField(
            model_name='gym',
            name='enable_trainers',
            field=models.BooleanField(default=True, help_text='Trainer management module.'),
        ),
    ]
