# Generated by Django 5.2.12 on 2026-06-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_gym_enable_attendance_gym_enable_face_recognition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymGSTProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_business_name', models.CharField(help_text='As per GST registration', max_length=255)),
                ('gstin', models.CharField(blank=True, help_text='15-char GSTIN, blank if unregistered', max_length=15)),
                ('is_gst_registered', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(help_text="GST state code, e.g. '22' for Chhattisgarh", max_length=2)),
                ('pincode', models.CharField(max_length=6)),
                ('invoice_series_prefix', models.CharField(default='INV', help_text="e.g. 'INV' -> INV/2026-27/0001", max_length=10)),
                ('default_sac_membership', models.CharField(default='999652', help_text='SAC for gym/fitness services', max_length=8)),
                ('signature_image', models.URLField(blank=True, help_text='Cloudinary URL of signature/stamp')),
                ('composition_scheme', models.BooleanField(default=False, help_text='If true, issue Bill of Supply instead of Tax Invoice — no GST shown')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_profile', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'GST Profile',
            },
        ),
    ]
