# Generated by Django 5.2.12 on 2026-06-28 00:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_gymgstprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gym_favicon'),
        ),
    ]
