# Generated by Django 5.2.12 on 2026-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_gym_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='map',
            field=models.URLField(blank=True),
        ),
    ]
