# Generated by Django 5.2.12 on 2026-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0006_gym_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='map',
            field=models.TextField(blank=True),
        ),
    ]
