# Generated by Django 5.2.12 on 2026-06-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0007_alter_gym_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='embedding_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
