# Generated by Django 5.2.12 on 2026-07-01 07:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0008_gym_embedding_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='app_download_url',
            field=models.URLField(blank=True, help_text="APK download link or Play Store URL for this gym's app."),
        ),
        migrations.AddField(
            model_name='gym',
            name='app_name',
            field=models.CharField(blank=True, help_text="Full application name shown during installation (e.g. 'Muscle Garage Fitness'). Falls back to gym_name if left blank.", max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='app_short_name',
            field=models.CharField(blank=True, help_text="Short name shown below the app icon (e.g. 'MuscleGarage'). Falls back to gym_name if blank.", max_length=30),
        ),
        migrations.AddField(
            model_name='gym',
            name='receipt_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='splash_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gym_splash_logo'),
        ),
        migrations.AddField(
            model_name='gym',
            name='theme_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='gym',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Primary square logo, recommended 512×512. Used as the 192×192 PWA icon.', max_length=255, null=True, verbose_name='gym_logo'),
        ),
    ]
