# Generated by Django 5.2.12 on 2026-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0009_gym_app_download_url_gym_app_name_gym_app_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='upi_display_name',
            field=models.CharField(blank=True, help_text="Name shown in the member's UPI app during payment.", max_length=120),
        ),
        migrations.AddField(
            model_name='gym',
            name='upi_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. yourgym@oksbi', max_length=100),
        ),
        migrations.AddField(
            model_name='gym',
            name='upi_payment_note',
            field=models.CharField(default='Membership Payment', help_text='Transaction note (tn) attached to the UPI deep link.', max_length=120),
        ),
    ]
