# Generated by Django 5.2.12 on 2026-07-08 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0010_gym_upi_display_name_gym_upi_enabled_gym_upi_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('period_start', models.DateField(help_text='Billing period this payment covers (start)')),
                ('period_end', models.DateField(help_text='Billing period this payment covers (end)')),
                ('notes', models.CharField(blank=True, help_text="e.g. UPI ref no., 'cash', 'renewal'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='Gym.gym')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_payments', to='Gym.subscriptionplan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Subscription Payment',
                'verbose_name_plural': 'Platform Subscription Payments',
                'ordering': ['-paid_on'],
                'indexes': [models.Index(fields=['gym', 'paid_on'], name='Gym_platfor_gym_id_d28271_idx')],
            },
        ),
    ]
