# Generated by Django 5.2.12 on 2026-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0011_platformsubscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('blue', 'Blue'), ('black', 'Black'), ('pink', 'Pink'), ('green', 'Green'), ('red', 'Red')], default='default', help_text="Predefined UI color palette for this gym's dashboard/site.", max_length=20),
        ),
    ]
