# Generated by Django 5.2.12 on 2026-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0012_gym_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='show_subscription_payment',
            field=models.BooleanField(default=False, help_text="When True, this gym's Owner/Receptionist see the 'Pay Subscription' button on their dashboard. Toggled only by the Super Admin from the All Gyms page. Has nothing to do with the existing payment gateway/upload system — this is purely a manual-payment flag."),
        ),
    ]
