# Generated by Django 5.2.12 on 2026-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0013_gym_show_subscription_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text="Your (Arrow SoftTech's) UPI ID for receiving gym subscription payments, e.g. yourname@oksbi", max_length=100)),
                ('upi_display_name', models.CharField(blank=True, help_text="Name shown in the gym owner's UPI app during payment, e.g. 'Arrow SoftTech'", max_length=120)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
