# Generated by Django 5.2.12 on 2026-07-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0014_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='last_expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last manual 'Send Expiry Reminder' click for this gym. Used to enforce a once-per-calendar-day limit. Compared against timezone.localdate() — not UTC date — so gyms see the limit reset at their local midnight from the server's perspective.", null=True),
        ),
    ]
