# Generated by Django 5.2.12 on 2026-07-13 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0015_gym_last_expiry_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_enrollment', models.BooleanField(default=False, verbose_name='Create Enrollment')),
                ('can_edit_enrollment', models.BooleanField(default=False, verbose_name='Edit Enrollment')),
                ('can_delete_enrollment', models.BooleanField(default=False, verbose_name='Delete Enrollment')),
                ('can_delete_duplicate_enrollment', models.BooleanField(default=False, verbose_name='Delete Duplicate Enrollment')),
                ('can_renew_membership', models.BooleanField(default=False, verbose_name='Renew Membership')),
                ('can_change_membership_plan', models.BooleanField(default=False, verbose_name='Change Membership Plan')),
                ('can_collect_payment', models.BooleanField(default=False, verbose_name='Collect Payment')),
                ('can_refund_payment', models.BooleanField(default=False, verbose_name='Refund Payment')),
                ('can_generate_invoice', models.BooleanField(default=False, verbose_name='Generate Invoice')),
                ('can_delete_invoice', models.BooleanField(default=False, verbose_name='Delete Invoice')),
                ('can_manage_membership_plans', models.BooleanField(default=False, verbose_name='Manage Membership Plans')),
                ('can_manage_trainers', models.BooleanField(default=False, verbose_name='Manage Trainers')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='Manage Staff')),
                ('can_view_dashboard', models.BooleanField(default=False, verbose_name='View Dashboard')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='View Reports')),
                ('can_view_revenue', models.BooleanField(default=False, verbose_name='View Revenue')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Export Reports')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Settings')),
                ('can_manage_upi', models.BooleanField(default=False, verbose_name='UPI')),
                ('can_manage_gst', models.BooleanField(default=False, verbose_name='GST')),
                ('can_manage_subscription', models.BooleanField(default=False, verbose_name='Manage Subscription')),
                ('can_delete_contacts', models.BooleanField(default=False, verbose_name='Delete Contacts')),
                ('can_manage_face_recognition', models.BooleanField(default=False, verbose_name='Face Recognition')),
                ('can_manage_attendance', models.BooleanField(default=False, verbose_name='Attendance')),
                ('can_send_expiry_notifications', models.BooleanField(default=False, verbose_name='Send Expiry Reminder')),
                ('can_manage_notifications', models.BooleanField(default=False, verbose_name='Push Notifications')),
                ('can_manage_store', models.BooleanField(default=False, verbose_name='Store (General)')),
                ('can_manage_products', models.BooleanField(default=False, verbose_name='Products')),
                ('can_manage_orders', models.BooleanField(default=False, verbose_name='Orders')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Gym.staffprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'verbose_name_plural': 'Staff Permissions',
            },
        ),
    ]
