# Generated by Django 5.2.12 on 2026-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0017_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_monthly']},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='active',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlanPricing',
        ),
    ]
