# Generated by Django 5.2.12 on 2026-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0018_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='enable_geo_attendance',
            field=models.BooleanField(default=False, help_text='GPS-based geo-fenced attendance specifically. Independent ofenable_attendance (which just controls the Attendance module/UI visibility) and enable_face_recognition. Turn this off for gyms using only Face Recognition, a biometric device, or no GPS check-in at all — this stops all location JS, Service Worker polling, and geo API calls for that gym.'),
        ),
    ]
