# Generated by Django 5.2.12 on 2026-07-17 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0019_gym_enable_geo_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanUserDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_id', models.PositiveIntegerField()),
                ('username', models.CharField(help_text='Phone number / username at time of deletion', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Orphan user cleanup — not linked to any gym', max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphan_deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orphan User Deletion Log',
                'verbose_name_plural': 'Orphan User Deletion Logs',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='Gym_orphanu_deleted_a5f4e3_idx')],
            },
        ),
    ]
