# Generated by Django 5.2.12 on 2026-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0020_orphanuserdeletionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='equipment_brands/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Brand',
                'verbose_name_plural': 'Equipment Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='equipment_brands',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='Gym.equipmentbrand'),
        ),
    ]
