# Generated by Django 5.2.12 on 2026-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0021_equipmentbrand_gym_equipment_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('icon', models.CharField(blank=True, default='fa-check', help_text='Optional Font Awesome class, used as a fallback if you ever render services without images (e.g. a compact list).', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order everywhere this catalog is listed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='Gym.service'),
        ),
    ]
