# Generated by Django 5.2.12 on 2026-07-19 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0022_service_gym_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='brand_logo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service_image'),
        ),
    ]
