# Generated by Django 5.2.12 on 2026-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0023_alter_equipmentbrand_logo_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentbrand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentbrand',
            name='website',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='website',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='gym',
            name='instagram_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
