# Generated by Django 5.2.12 on 2026-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0024_add_gym_social_media_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('blue', 'Blue'), ('black', 'Black'), ('pink', 'Pink'), ('green', 'Green'), ('red', 'Red'), ('custom', 'Custom')], default='default', help_text="Predefined UI color palette for this gym's dashboard/site.", max_length=20),
        ),
    ]
