# Generated by Django 5.2.12 on 2026-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0025_alter_gym_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='dashboard_mode',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Dark or light background for the dashboard UI.', max_length=10),
        ),
    ]
