# Generated by Django 5.2.12 on 2026-07-25 12:15

import Gym.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0014_membershipplan_show_on_home_registerscanimport_and_more'),
        ('Gym', '0026_gym_dashboard_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_send_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Send WhatsApp Messages'),
        ),
        migrations.CreateModel(
            name='GymWhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. When False, no WhatsApp message is ever sent for this gym, regardless of individual notification triggers.')),
                ('business_name', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, help_text="Gym's WhatsApp Business number in E.164 format, e.g. +919876543210", max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +919876543210 or +14155552671.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('business_account_id', models.CharField(blank=True, max_length=64)),
                ('permanent_access_token', Gym.fields.EncryptedTextField(blank=True, default='')),
                ('webhook_verify_token', Gym.fields.EncryptedTextField(blank=True, default='')),
                ('webhook_secret', Gym.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_configured', 'Not Configured'), ('pending', 'Pending Verification'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='not_configured', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Gym WhatsApp Settings',
                'verbose_name_plural': 'Gym WhatsApp Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Destination WhatsApp number at send time, E.164 format — stored independently of `member` so the log stays readable even if member is later nulled out.', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, e.g. +919876543210 or +14155552671.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('document', 'Document'), ('location', 'Location'), ('interactive_buttons', 'Interactive Buttons')], max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('deduplication_key', models.CharField(blank=True, db_index=True, default='', help_text="Deterministic key identifying the business event this message represents, e.g. 'expiry_reminder:{enrollment_id}:{due_date}'. Used to guarantee at-most-one successful send per event.", max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, help_text="Meta's `messages[0].id` from a successful send — used to correlate with delivery/read webhook events later.", max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('read', 'Read')], db_index=True, default='queued', max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_message_logs', to='Gym.gym')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_message_logs', to='AuthFit.enrollment')),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'created_at'], name='Gym_whatsap_gym_id_3d5360_idx'), models.Index(fields=['gym', 'status'], name='Gym_whatsap_gym_id_d09aab_idx'), models.Index(fields=['gym', 'message_type'], name='Gym_whatsap_gym_id_46a4e0_idx'), models.Index(fields=['gym', 'deduplication_key'], name='Gym_whatsap_gym_id_22ff68_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), fields=('gym', 'deduplication_key'), name='unique_whatsapp_dedup_key_per_gym')],
            },
        ),
    ]
