# Generated by Django 5.2.12 on 2026-07-26 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0027_staffpermission_can_send_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymwhatsappsettings',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Day Before'), (3, '3 Days Before'), (5, '5 Days Before'), (7, '7 Days Before')], default=3, help_text='How many days before membership expiry the WhatsApp reminder should be sent. Only ONE reminder is sent at this exact offset — not on every day counting down to it.'),
        ),
        migrations.AddField(
            model_name='gymwhatsappsettings',
            name='reminder_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), 'Morning (09:00)'), (datetime.time(14, 0), 'Afternoon (14:00)'), (datetime.time(18, 0), 'Evening (18:00)')], default=datetime.time(9, 0), help_text="Time of day (in this gym's configured timezone) when the WhatsApp expiry reminder should be sent. Requires the expiry-reminder cron to run at least as often as the configured time slots (recommended: 09:00, 14:00, 18:00)."),
        ),
        migrations.AddField(
            model_name='gymwhatsappsettings',
            name='send_post_expiry_reminder',
            field=models.BooleanField(default=True, help_text='Whether to send exactly one WhatsApp reminder the day after membership expires (days_left == -1 only — not repeated on subsequent overdue days).'),
        ),
        migrations.AddField(
            model_name='gymwhatsappsettings',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata (IST)'), ('Asia/Dubai', 'Asia/Dubai (GST)'), ('Europe/London', 'Europe/London (GMT/BST)'), ('America/New_York', 'America/New_York (ET)'), ('Australia/Sydney', 'Australia/Sydney (AET)')], default='Asia/Kolkata', help_text='IANA timezone used to evaluate reminder_time for this gym.', max_length=50),
        ),
    ]
