# Generated by Django 5.2.12 on 2026-07-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthFit', '0014_membershipplan_show_on_home_registerscanimport_and_more'),
        ('Gym', '0028_gymwhatsappsettings_reminder_days_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('fcm', 'FCM (Mobile App)'), ('web_push', 'Web Push (Browser/PWA)')], max_length=20)),
                ('notif_type', models.CharField(blank=True, choices=[('plan_expiry', 'Plan Expiry Reminder'), ('plan_changed', 'Plan Changed'), ('renewal_reminder', 'Renewal Reminder'), ('member_message', 'Staff Message')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('success', models.BooleanField(db_index=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification_logs', to='Gym.gym')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notification_logs', to='AuthFit.enrollment')),
            ],
            options={
                'verbose_name': 'Push Notification Log',
                'verbose_name_plural': 'Push Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'created_at'], name='Gym_pushnot_gym_id_b99279_idx'), models.Index(fields=['gym', 'success'], name='Gym_pushnot_gym_id_a7c282_idx')],
            },
        ),
    ]
