# Generated by Django 5.2.12 on 2026-07-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0029_pushnotificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_voided', 'Invoice Voided'), ('payment_received', 'Payment Received'), ('refund_issued', 'Refund Issued'), ('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_deleted', 'Expense Deleted'), ('membership_renewed', 'Membership Renewed'), ('plan_changed', 'Plan Changed'), ('enrollment_deleted', 'Enrollment Deleted')], db_index=True, max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_label', models.CharField(blank=True, help_text='Human-readable snapshot, e.g. invoice number or member name — survives even if the referenced row is later deleted.', max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='Gym.gym')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'created_at'], name='Gym_auditlo_gym_id_cde63b_idx'), models.Index(fields=['gym', 'action'], name='Gym_auditlo_gym_id_23730a_idx'), models.Index(fields=['object_type', 'object_id'], name='Gym_auditlo_object__547bd3_idx')],
            },
        ),
    ]
