# Generated by Django 5.2.12 on 2026-07-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0030_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAICredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=10)),
                ('total_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'Gym AI Credit Wallet',
                'verbose_name_plural': 'Gym AI Credit Wallets',
            },
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(help_text='Positive for a credit added, negative for a deduction.')),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_transactions', to='Gym.gym')),
            ],
            options={
                'verbose_name': 'AI Credit Transaction',
                'verbose_name_plural': 'AI Credit Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', 'created_at'], name='Gym_aicredi_gym_id_3850f6_idx')],
            },
        ),
    ]
