# Generated by Django 5.2.12 on 2026-07-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0031_gymaicredit_aicredittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='hidden_stat_cards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
