# Generated by Django 5.2.12 on 2026-07-29 17:34

import Gym.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0032_gym_hidden_stat_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymwhatsappsettings',
            name='webhook_secret',
            field=Gym.fields.EncryptedTextField(blank=True, default='', help_text='DEPRECATED — no longer used. Webhook signature validation now uses the platform-wide settings.WHATSAPP_APP_SECRET. Retained on this model only to avoid a destructive migration on existing rows; never read or written by current code.'),
        ),
        migrations.AlterField(
            model_name='gymwhatsappsettings',
            name='webhook_verify_token',
            field=Gym.fields.EncryptedTextField(blank=True, default='', help_text='DEPRECATED — no longer used. Webhook verification now uses the platform-wide settings.WHATSAPP_VERIFY_TOKEN. Retained on this model only to avoid a destructive migration on existing rows; never read or written by current code.'),
        ),
    ]
