# Generated by Django 5.2.12 on 2026-08-15 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0034_gym_pending_amount_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffprofile',
            constraint=models.UniqueConstraint(fields=('user', 'gym'), name='unique_staffprofile_per_user_per_gym'),
        ),
    ]
